server:
  port: 7788

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customer/**

        - id: ADDRESS-SERVICE
          uri: lb://ADDRESS-SERVICE
          predicates:
            - Path=/api/address/**
            
        - id: CBI-DISCOVERY
          uri: http://localhost:8761
          predicates:
            - Path=/**

message: APIGateway - Dev Config Loaded from Config Server