server:
  port: 1212

spring:
  application:
    name: CUSTOMER-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mageshit2025
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

address:
  server:
    url: http://localhost:1122/api/address
microservice:
  service:
    name: ADDRESS-SERVICE
