server:
  port: 1212

spring:
  application:
    name: CUSTOMER-SERVICE
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@prod-db:1521/orclpdb
    username: prod_user
    password: Prod@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
